#文件上传配置

lin:
  file:
    # 文件服务域名
    domain: http://localhost:5000/
    # 排除文件类型
    exclude:
    # 包括文件类型
    include:
      - .jpg
      - .png
      - .jpeg
    # 文件最大数量
    nums: 10
    # 服务器文件路径
    serve-path: assets/**
    # 单个文件最大体积
    single-limit: 2MB
    # 本地文件保存位置
    store-dir: assets/
spring:
  servlet:
    multipart:
      # 总体文件最大体积（只能从max-file-size设置总体文件的大小）
      max-file-size: 20MB
