name: Java CI with Maven

on:
  push:
    branches:
      - server-demo

jobs:
  build:
    name: 编译
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8,9,11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  deploy:
    name: 部署
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装 JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 编译
        run: mvn -B package --file pom.xml
      - name: 删除旧版本 jar 包
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/docker/project/lin_cms_springboot_demo/app
            rm -rf latticy-*.jar
      - name: 上传 jar 包
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: "-rltgoDzvO"
          SOURCE: "target/latticy-*.jar"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: 启动程序
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/docker/project/lin_cms_springboot_demo
            docker-compose up -d